### ISSUE TITLE
Implement MySQL adapter

### ISSUE THREAD

**Issue by w3q** [MillianGroup/Apison#2]
Implement MySQL Adapter functionality defined by DbAdapterInterface.

**Comment by w3q** [comment]
Is whole MySQL adapter implemented? Is there any functionality needed to implement? If you will finish implementation of mysql "id IN (1,2,3)" clause, I suppose this issue should be closed.

**Comment by Franky238** [comment]
tomorow i implement IN clausule .. after i mark it as need review and next close

**Comment by Franky238** [comment]
done! now closing
